  build:
    runs-on: windows-2025
    needs: get-info
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Ninja
      run: choco install ninja

    - name: Setup VS Environment
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: amd64

    - name: Setup Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.2
        host: windows
        target: desktop
        arch: win64_msvc2022_64

    - name: Configure CMake
      run: cmake --fresh -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $env:NUMBER_OF_PROCESSORS

    - name: Deploy Qt Dependencies
      run: |
        "${{ env.Qt6_DIR }}/bin/windeployqt.exe" --release --dir ${{github.workspace}}/build ${{github.workspace}}/build/lidar.exe

    - name: Run tests
      run: ctest --test-dir build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ${{github.workspace}}/build
