name: Build Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        vsversion: 2022
        arch: amd64

    - name: Set up Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2022_64'
        dir: '${{ env.HOME }}/Qt'

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_PREFIX_PATH=${{ env.HOME }}/Qt/6.8.2/msvc2019_64

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build
