name: Build and Release

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Ninja
        run: choco install ninja

      - name: Setup Visual Studio Environment
        uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: amd64

      - name: Cache Qt Installation
        uses: actions/cache@v4
        with:
          path: |
            C:/Qt/6.8.2/msvc2022_64
          key: qt-${{ runner.os }}-6.8.2-msvc2022_64
          restore-keys: |
            qt-${{ runner.os }}-6.8.2-msvc2022_64

      - name: Setup Qt with Required Modules
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          modules: qtcharts qtserialport

      - name: Configure CMake
        run: |
          cmake --fresh -G Ninja -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="C:/Qt/6.8.2/msvc2022_64"

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel $env:NUMBER_OF_PROCESSORS

      - name: Manually Copy Qt DLLs
        run: |
          copy "C:/Qt/6.8.2/msvc2022_64/bin/Qt6Core.dll" build/
          copy "C:/Qt/6.8.2/msvc2022_64/bin/Qt6Gui.dll" build/
          copy "C:/Qt/6.8.2/msvc2022_64/bin/Qt6Widgets.dll" build/
          copy "C:/Qt/6.8.2/msvc2022_64/bin/Qt6SerialPort.dll" build/
          copy "C:/Qt/6.8.2/msvc2022_64/bin/Qt6Charts.dll" build/

      - name: Run tests
        run: ctest --test-dir build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build
