name: Build Qt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: actions-setup-cmake
      uses: jwlawson/actions-setup-cmake@v2.0.2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.8.2'
        host: 'linux'
        target: 'desktop'
        arch: 'linux_gcc_64'
        dir: '$HOME/Qt'


    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_PREFIX_PATH=$HOME/Qt/6.8.2/gcc_64

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build
